development:
  adapter: postgresql
  encoding: unicode
  database: gello_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gello_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gello_production
  pool: 5
  username: 
  password:
